# Generated by Django 2.2 on 2023-09-02 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.PositiveIntegerField(max_length=20),
        ),
        migrations.CreateModel(
            name='bookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(max_length=20, unique=True)),
                ('booking_name', models.CharField(max_length=225)),
                ('booking_email', models.EmailField(max_length=254)),
                ('booking_phone', models.PositiveIntegerField(max_length=20)),
                ('booking_date', models.DateField(default=None)),
                ('booking_plan', models.CharField(max_length=100)),
                ('total_coast', models.BigIntegerField(max_length=10)),
                ('booking_status', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.planModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
