# Generated by Django 2.2 on 2023-09-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_auto_20230902_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='total_coast',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='duration',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='total_cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='booking_phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
