# Generated by Django 2.2 on 2023-09-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0006_auto_20230903_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='booking_phone',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.BigIntegerField(default=None),
        ),
    ]
