# Generated by Django 2.2 on 2023-09-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0007_auto_20230903_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='booking_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
