# Generated by Django 2.2 on 2023-09-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0008_auto_20230903_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='booking_code',
            field=models.CharField(max_length=20),
        ),
    ]
