# Generated by Django 2.2 on 2023-09-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0009_auto_20230904_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='booking_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
