# Generated by Django 2.2 on 2023-09-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0010_auto_20230904_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='booking_code',
            field=models.CharField(max_length=20),
        ),
    ]
