# Generated by Django 2.2 on 2023-09-10 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0013_auto_20230904_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.userModel'),
        ),
    ]
